version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nft_minter
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # Uncomment this service to use a local blockchain for development
  # ganache:
  #   image: trufflesuite/ganache-cli:latest
  #   ports:
  #     - "8545:8545"
  #   command:
  #     - "--deterministic"
  #     - "--mnemonic=test test test test test test test test test test test junk"
  #     - "--networkId=1337"
  #     - "--chainId=1337"

  turbo-cache:
    image: ghcr.io/vercel/turborepo-remote-cache:latest
    container_name: turborepo-cache
    restart: always
    ports:
      - "3072:3000"
    environment:
      - TURBO_TOKEN=your-secret-token # Choose a secure token
      - STORAGE_PROVIDER=local
      - STORAGE_PATH=/app/data
    volumes:
      - ./data:/app/data

volumes:
  postgres-data:
  redis-data:
  data:
    driver: local 