version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nft-minter-app
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
    networks:
      - nft-network

networks:
  nft-network:
    driver: bridge 