version: '3.8'

services:
  api:
    container_name: nft-minter-api
    build: .
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_DATABASE=nft_minter
      - DATABASE_URL=postgresql://postgres:example@db:5432/nft_minter
      - ETHERSCAN_API_KEY=your-etherscan-api-key-here
      - ETHERSCAN_API_ENDPOINT=https://api.etherscan.io/v2/api
      - ETH_RPC_URL=https://sepolia.infura.io/v3/your-infura-project-id-here
      - OPENSEA_API_KEY=your-opensea-api-key-here
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRATION=1d
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=your-openai-api-key-here

    depends_on:
      - db
      - redis
    networks:
      - nft-network

  db:
    container_name: nft-minter-db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nft_minter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nft-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - nft-network

volumes:
  postgres_data:
    driver: local

networks:
  nft-network:
    driver: bridge 