name: Frontend Deploy

on:
  push:
    branches: [main]
    paths:
      - 'apps/frontend/**'
      - 'packages/shared/**'
      - '.github/workflows/frontend-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    # Optional - if you have Vercel deployment set up
    # env:
    #   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    #   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    #   VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: npm run build --filter=@nft-minter/shared

      - name: Build frontend
        run: npm run build --filter=nft-minter-front
        env:
          # Add any environment variables needed for build
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      # Uncomment if using Vercel for deployment
      # - name: Install Vercel CLI
      #   run: npm install --global vercel@latest

      # - name: Deploy to Vercel
      #   run: |
      #     cd apps/frontend
      #     vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      # Or if you're deploying to other platforms, add your deployment steps here
      # For example, for AWS S3 + CloudFront:
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      
      # - name: Deploy to S3
      #   run: |
      #     aws s3 sync ./apps/frontend/.next/static s3://your-bucket/next/_next/static/ --delete
      #     aws s3 sync ./apps/frontend/public s3://your-bucket/ --delete
      #     aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*" 