name: Turborepo Remote Cache

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  cache-and-test:
    name: Build and Test with Remote Cache
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # This enables turborepo to use the remote cache
      - name: Build with Remote Cache
        run: npm run build

      # Run tests using the remote cache for any computed dependencies
      - name: Test with Remote Cache
        run: npm run test 